services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: tomcat:11
    ports:
      - '8080:8080'
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    volumes:
      - ./target/weather.war:/usr/local/tomcat/webapps/weather.war
    depends_on:
      - db

volumes:
  pgdata: